---
# vim: set ft=yaml.ansible:

- name: "setup neovim"
  hosts: all
  gather_facts: no

  tasks:
    - name: "create vim-plug dir"
      file:
        path: "~/.local/share/nvim/site/autoload"
        mode: 0700
        state: directory

    - name: "install vim-plug"
      get_url:
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        dest: "~/.local/share/nvim/site/autoload/plug.vim"

    - name: "update vim plugins"
      command: "nvim -es -u ~/.config/nvim/init.vim -i NONE -c 'PlugInstall' -c 'qa'"

    - name: "install python dev tools"
      pip:
        name:
          - yapf
          - jedi
          - isort
        executable: /usr/bin/pip3
