---
# vim: set ft=yaml.ansible:

- name: "setup zsh"
  hosts: all
  gather_facts: no

  vars_files:
    - "../vars.yml"

  tasks:
    - name: "clone oh-my-zsh repo"
      git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: "{{ omz_dir }}"
        version: master

    - name: "change to zsh"
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: "install zsh-syntax-highlighting"
      git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
        dest: "{{ omz_dir }}/custom/plugins/zsh-syntax-highlighting"
        version: master

    - name: "install zsh-autosuggestions"
      git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
        dest: "{{ omz_dir }}/custom/plugins/zsh-autosuggestions"
        version: master
